/* CRIAÇÃO DA CONSTANTE QUE REPESENTA O NOME DO BANCO DE DADOS: */
const database = 'BD3-AULA';

/* CRIAÇÃO DA CONSTANTE QUE REPESENTA O NOME DA COLEÇÃO DE ARQUIVOS: */
const collection = 'LIVRARIA';

/* DEFINE O BANCO DE DADOS QUE SERÁ UTILIZADO, CASO NÃO EXISTA SERÁ CRIADO */
use(database);

/* SELECIONA OS DADOS DE TODOS OS ARQUIVOS SEM CRITÉRIOS: */
//db['LIVRARIA'].find();

/* SELECIONA OS DADOS DE TODOS OS ARQUIVOS COM A CATEGORIA DEFINIDA: */
//db['LIVRARIA'].find({"categoria":"Fantasia Heroica"});

/* SELECIONA OS DADOS DE TODOS OS ARQUIVOS COM A CATEGORIA DEFINIDA E OCULTANDO CERTOS CAMPOS: */
/*db['LIVRARIA'].find(
     {"categoria":"Fantasia Heroica"},
    {_id:0, codigo:0, descricao:0}
    );
*/

/* SELECIONA ARQUIVOS QUE CONTENHAM UMA INCIDENCIA ESPECIFICA DE TEXTO: */
db['LIVRARIA'].find({"descricao": /hobbit/i});